-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.flights
(
    id_flights integer NOT NULL,
    id_plane integer,
    id_rout integer,
    start time with time zone,
    "end" time with time zone,
    free_tickets integer,
    PRIMARY KEY (id_flights)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user integer NOT NULL,
    login text,
    password text,
    full_name text,
    PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.request_history
(
    "id_request " integer NOT NULL,
    id_user integer,
    "request " text,
    PRIMARY KEY ("id_request ")
);

CREATE TABLE IF NOT EXISTS public.favorite_city
(
    id_city integer NOT NULL,
    id_user integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.city
(
    id_city integer NOT NULL,
    name text,
    description text,
    visible_count integer,
    id_popular_location integer,
    PRIMARY KEY (id_city)
);

CREATE TABLE IF NOT EXISTS public.popular_places
(
    id_place integer NOT NULL,
    id_city integer,
    name text,
    located text,
    path_img text,
    description text,
    PRIMARY KEY (id_place)
);

CREATE TABLE IF NOT EXISTS public.route
(
    id_route integer NOT NULL,
    id_from integer,
    id_to integer,
    stop integer,
    price integer,
    PRIMARY KEY (id_route)
);

CREATE TABLE IF NOT EXISTS public.plans
(
    id_plan integer NOT NULL,
    contry text,
    max_ticket integer,
    PRIMARY KEY (id_plan)
);

ALTER TABLE IF EXISTS public.flights
    ADD FOREIGN KEY (id_rout)
    REFERENCES public.route (id_route) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flights
    ADD FOREIGN KEY (id_plane)
    REFERENCES public.plans (id_plan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.request_history
    ADD FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.favorite_city
    ADD FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.favorite_city
    ADD FOREIGN KEY (id_city)
    REFERENCES public.city (id_city) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.popular_places
    ADD FOREIGN KEY (id_city)
    REFERENCES public.city (id_city) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.route
    ADD FOREIGN KEY (id_from)
    REFERENCES public.city (id_city) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.route
    ADD FOREIGN KEY (id_to)
    REFERENCES public.city (id_city) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;