-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.flights
(
    id_flights integer NOT NULL,
    id_plane integer,
    country_plan text,
    to_city text,
    from_city text,
    start time with time zone,
    "end" time with time zone,
    stop integer,
    price double precision,
    PRIMARY KEY (id_flights)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user integer NOT NULL,
    login text,
    password text,
    name text,
    surname text,
    year_birth date,
    gender text,
    phone text,
    country text,
    PRIMARY KEY (id_user)
);
END;