-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.flights
(
    id_flights integer NOT NULL,
    id_plane integer,
    country_plan text,
    "to" text,
    "from" text,
    start time with time zone,
    "end" time with time zone,
    stop integer,
    price double precision,
    PRIMARY KEY (id_flights)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user integer NOT NULL,
    login text,
    password text,
    full_name text,
    PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.request_history
(
    "id_request " integer NOT NULL,
    id_user integer,
    "request " text,
    PRIMARY KEY ("id_request ")
);

CREATE TABLE IF NOT EXISTS public.favorite_city
(
    city_name text NOT NULL,
    id_user integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.city
(
    name text NOT NULL,
    visible_count integer,
    PRIMARY KEY (name)
);

ALTER TABLE IF EXISTS public.flights
    ADD FOREIGN KEY ("to")
    REFERENCES public.city (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flights
    ADD FOREIGN KEY ("from")
    REFERENCES public.city (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.request_history
    ADD FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.favorite_city
    ADD FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.favorite_city
    ADD FOREIGN KEY (city_name)
    REFERENCES public.city (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;