# Generated by Django 5.0.6 on 2024-06-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalLocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.TextField(null=True),
        ),
    ]
