# Generated by Django 5.0.6 on 2024-05-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalLocker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPersonalData',
        ),
    ]
