# Generated by Django 5.0.6 on 2024-06-01 19:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalLocker', '0002_alter_customuser_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=None),
        ),
    ]
